const CHANGE_RED = 'CHANGE_RED'
const CHANGE_WHITE = 'CHANGE_WHITE'
const CHANGE_USER_STATE = ' CHANGE_USER_STATE'
const CHANGE_USER_INFO = 'CHANGE_USER_INFO'
const USER_NAME = 'USER_NAME'
const CHANGE_CATEGORY_LIST = 'CHANGE_CATEGORY_LIST'

export  { CHANGE_USER_RED, CHANGE_WHITE,CHANGE_USER_INFO,CHANGE_USER_STATE,CHANGE_CATEGORY_LIST }